name: CI/CD #the name of our pipeline

on:
  push:
    branches:
      - main #Run this workflow whenever someone pushes code to the main branch
  pull_request:
    branches:
      - main #also run when someone creates a Pull Request targeting main
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  validate:
    runs-on: ubuntu-latest #temporary Linux runner to execute our job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #Download/checkout the repository's code so the following steps can work with it.

      - name: Check HTML file exists
        run: test -f index.html
        
  deploy:
    needs: validate #Don't deploy unless validation succeeds.
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload website
        uses: actions/upload-pages-artifact@v3 #"The files produced/prepared by the pipeline that we want to pass to the next stage."
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4